/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1beta1 "halkyon.io/api/runtime/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeRuntimes implements RuntimeInterface
type FakeRuntimes struct {
	Fake *FakeHalkyonV1beta1
}

var runtimesResource = schema.GroupVersionResource{Group: "halkyon.io", Version: "v1beta1", Resource: "runtimes"}

var runtimesKind = schema.GroupVersionKind{Group: "halkyon.io", Version: "v1beta1", Kind: "Runtime"}

// Get takes name of the runtime, and returns the corresponding runtime object, and an error if there is any.
func (c *FakeRuntimes) Get(name string, options v1.GetOptions) (result *v1beta1.Runtime, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(runtimesResource, name), &v1beta1.Runtime{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.Runtime), err
}

// List takes label and field selectors, and returns the list of Runtimes that match those selectors.
func (c *FakeRuntimes) List(opts v1.ListOptions) (result *v1beta1.RuntimeList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(runtimesResource, runtimesKind, opts), &v1beta1.RuntimeList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1beta1.RuntimeList{ListMeta: obj.(*v1beta1.RuntimeList).ListMeta}
	for _, item := range obj.(*v1beta1.RuntimeList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested runtimes.
func (c *FakeRuntimes) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(runtimesResource, opts))
}

// Create takes the representation of a runtime and creates it.  Returns the server's representation of the runtime, and an error, if there is any.
func (c *FakeRuntimes) Create(runtime *v1beta1.Runtime) (result *v1beta1.Runtime, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(runtimesResource, runtime), &v1beta1.Runtime{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.Runtime), err
}

// Update takes the representation of a runtime and updates it. Returns the server's representation of the runtime, and an error, if there is any.
func (c *FakeRuntimes) Update(runtime *v1beta1.Runtime) (result *v1beta1.Runtime, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(runtimesResource, runtime), &v1beta1.Runtime{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.Runtime), err
}

// Delete takes name of the runtime and deletes it. Returns an error if one occurs.
func (c *FakeRuntimes) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(runtimesResource, name), &v1beta1.Runtime{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeRuntimes) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(runtimesResource, listOptions)

	_, err := c.Fake.Invokes(action, &v1beta1.RuntimeList{})
	return err
}

// Patch applies the patch and returns the patched runtime.
func (c *FakeRuntimes) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.Runtime, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(runtimesResource, name, pt, data, subresources...), &v1beta1.Runtime{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.Runtime), err
}
